<?php

$title = 'détails du post ';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?> <?= $this->escapeHtml($details->titre) ?> posté le  <?= $this->escapeHtml($details->date) ?></h1>


<h5 class="card-title"><?= $this->escapeHtml($details->titre) ?></h5>
        <p><?= $this->escapeHtml($details->auteur) ?></p>
<p style="white-space: pre-line"><?= $this->escapeHtml($details->texte) ?></p>
        <p><a href="<?= $this->url('Blog', ['action' => 'delete', 'id' => $details->id]) ?>">Supprimer ce post</a></p>
        <p><li> <a href="<?= $this->url('Blog', ['action' => 'edit', 'id' => $details->id]) ?>">Modifier ce post</a></td></li></p>

